-- These tables are accessed only through the authenticated backend, never
-- through public Supabase Data API roles. Preserve the existing deny-all model.
ALTER TABLE "AgentIdentity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgentGatewayPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DecisionRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AcpCheckoutSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AcpDelegatedPayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CatalogCompilation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignConversion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignOrderAttribution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Refund" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReturnRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReturnItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Fulfillment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FulfillmentItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Dispute" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BuyerSpendingPolicy" ENABLE ROW LEVEL SECURITY;
