-- PART 05 — Deterministic Policy Engine, Approval Lifecycle, Execution
-- Authorization, and the Agent Action Ledger hash chain.

-- AlterEnum
ALTER TYPE "AgentActorType" ADD VALUE 'MERCHANT_USER';

-- CreateEnum
CREATE TYPE "ApprovalDecision" AS ENUM ('APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "ExecutionAuthorizationStatus" AS ENUM ('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED');

-- AlterEnum
ALTER TYPE "GrowthProposalStatus" ADD VALUE 'POLICY_DENIED';
ALTER TYPE "GrowthProposalStatus" ADD VALUE 'ALLOWED';
ALTER TYPE "GrowthProposalStatus" ADD VALUE 'PENDING_APPROVAL';
ALTER TYPE "GrowthProposalStatus" ADD VALUE 'APPROVED';
ALTER TYPE "GrowthProposalStatus" ADD VALUE 'APPROVAL_REJECTED';
ALTER TYPE "GrowthProposalStatus" ADD VALUE 'AUTHORIZED';

-- AlterTable: MerchantPolicy — replace the PART 01 placeholder shape (a
-- single maxDiscountPercent ceiling, no auto-approval/hard-max distinction)
-- with the real bps-based, versioned shape PART 05's Policy Engine reads.
-- The single existing row per merchant is synthetic demo configuration
-- (re-seeded via `pnpm db:seed`), so this is a plain column swap rather
-- than a data-preserving migration.
ALTER TABLE "MerchantPolicy"
  DROP COLUMN "maxDiscountMinor",
  DROP COLUMN "maxDiscountPercent",
  DROP COLUMN "approvalThresholdMinor",
  ADD COLUMN "policyVersion" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "maxDiscountBps" INTEGER NOT NULL DEFAULT 1000,
  ADD COLUMN "autoApprovalDiscountBps" INTEGER NOT NULL DEFAULT 300,
  ADD COLUMN "autoApprovalOrderAmountMinor" INTEGER NOT NULL DEFAULT 1000000,
  ADD COLUMN "proposalValidityMinutes" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN "approvalValidityMinutes" INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN "authorizationValidityMinutes" INTEGER NOT NULL DEFAULT 10;

-- AlterTable: GrowthActionProposal — denormalized pointers to the latest
-- governance records, maintained transactionally alongside `status`.
ALTER TABLE "GrowthActionProposal"
  ADD COLUMN "latestPolicyDecisionId" TEXT,
  ADD COLUMN "approvalId" TEXT,
  ADD COLUMN "executionAuthorizationId" TEXT;

-- AlterTable: AgentAction — introduce the per-workflow hash chain. Existing
-- rows predate this requirement and are 100% synthetic demo/audit data
-- regenerated by `pnpm db:seed` and ordinary agent runs (never real
-- financial records) — clearing them avoids fabricating a backfilled hash
-- chain for events that were never actually chained.
DELETE FROM "AgentAction";

ALTER TABLE "AgentAction"
  ADD COLUMN "sequence" INTEGER NOT NULL,
  ADD COLUMN "previousEventHash" TEXT,
  ADD COLUMN "eventHash" TEXT NOT NULL,
  ADD COLUMN "ledgerHashVersion" TEXT NOT NULL DEFAULT '1';

-- CreateIndex
CREATE UNIQUE INDEX "AgentAction_workflowId_sequence_key" ON "AgentAction"("workflowId", "sequence");

-- CreateIndex
CREATE INDEX "AgentAction_eventHash_idx" ON "AgentAction"("eventHash");

-- CreateTable
CREATE TABLE "PolicyEvaluation" (
    "id" TEXT NOT NULL,
    "proposalId" TEXT NOT NULL,
    "merchantId" TEXT NOT NULL,
    "workflowId" TEXT NOT NULL,
    "outcome" "PolicyDecision" NOT NULL,
    "reasonCodes" JSONB NOT NULL,
    "explanation" TEXT NOT NULL,
    "evaluatedPolicyVersion" INTEGER NOT NULL,
    "evaluatedValues" JSONB NOT NULL,
    "proposalFingerprint" TEXT NOT NULL,
    "fingerprintVersion" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PolicyEvaluation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Approval" (
    "id" TEXT NOT NULL,
    "proposalId" TEXT NOT NULL,
    "proposalFingerprint" TEXT NOT NULL,
    "merchantId" TEXT NOT NULL,
    "policyEvaluationId" TEXT NOT NULL,
    "evaluatedPolicyVersion" INTEGER NOT NULL,
    "decision" "ApprovalDecision" NOT NULL,
    "reason" TEXT,
    "approverId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Approval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ExecutionAuthorization" (
    "id" TEXT NOT NULL,
    "proposalId" TEXT NOT NULL,
    "proposalFingerprint" TEXT NOT NULL,
    "merchantId" TEXT NOT NULL,
    "policyEvaluationId" TEXT NOT NULL,
    "approvalId" TEXT,
    "authorizedActionType" "GrowthActionType" NOT NULL,
    "financialBounds" JSONB NOT NULL,
    "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "status" "ExecutionAuthorizationStatus" NOT NULL DEFAULT 'ACTIVE',
    "authorizationVersion" TEXT NOT NULL DEFAULT '1',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ExecutionAuthorization_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "PolicyEvaluation_proposalId_createdAt_idx" ON "PolicyEvaluation"("proposalId", "createdAt");

-- CreateIndex
CREATE INDEX "PolicyEvaluation_merchantId_createdAt_idx" ON "PolicyEvaluation"("merchantId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "Approval_proposalId_key" ON "Approval"("proposalId");

-- CreateIndex
CREATE INDEX "Approval_merchantId_createdAt_idx" ON "Approval"("merchantId", "createdAt");

-- CreateIndex
CREATE INDEX "ExecutionAuthorization_proposalId_idx" ON "ExecutionAuthorization"("proposalId");

-- CreateIndex
CREATE INDEX "ExecutionAuthorization_merchantId_createdAt_idx" ON "ExecutionAuthorization"("merchantId", "createdAt");

-- CreateIndex
CREATE INDEX "ExecutionAuthorization_status_expiresAt_idx" ON "ExecutionAuthorization"("status", "expiresAt");

-- CreateIndex: partial unique index — at most one ACTIVE authorization per
-- proposal, enforced at the database level (PART 05 §69), while still
-- allowing historical EXPIRED/REVOKED rows to accumulate for audit. Not
-- representable in `schema.prisma`'s DSL, hence hand-written here (this
-- project only ever applies migrations via `prisma migrate deploy`, never
-- `migrate dev`, so there is no drift-detection step to satisfy).
CREATE UNIQUE INDEX "ExecutionAuthorization_proposalId_active_key" ON "ExecutionAuthorization"("proposalId") WHERE "status" = 'ACTIVE';

-- AddForeignKey
ALTER TABLE "PolicyEvaluation" ADD CONSTRAINT "PolicyEvaluation_proposalId_fkey" FOREIGN KEY ("proposalId") REFERENCES "GrowthActionProposal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PolicyEvaluation" ADD CONSTRAINT "PolicyEvaluation_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_proposalId_fkey" FOREIGN KEY ("proposalId") REFERENCES "GrowthActionProposal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_policyEvaluationId_fkey" FOREIGN KEY ("policyEvaluationId") REFERENCES "PolicyEvaluation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExecutionAuthorization" ADD CONSTRAINT "ExecutionAuthorization_proposalId_fkey" FOREIGN KEY ("proposalId") REFERENCES "GrowthActionProposal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExecutionAuthorization" ADD CONSTRAINT "ExecutionAuthorization_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExecutionAuthorization" ADD CONSTRAINT "ExecutionAuthorization_policyEvaluationId_fkey" FOREIGN KEY ("policyEvaluationId") REFERENCES "PolicyEvaluation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExecutionAuthorization" ADD CONSTRAINT "ExecutionAuthorization_approvalId_fkey" FOREIGN KEY ("approvalId") REFERENCES "Approval"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
