import { useState } from "react";
import { AlertTriangle, Ban, Search, ShieldCheck } from "lucide-react";
import type { FailureFirstDemoDTO } from "@razorgrowth/contracts";
import { apiPost } from "../lib/api-client";
import { formatMoney } from "../lib/format";

export default function AdminRiskPage() {
  const [result, setResult] = useState<FailureFirstDemoDTO | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [running, setRunning] = useState(false);
  async function run() { setRunning(true); setError(null); try { setResult(await apiPost<FailureFirstDemoDTO>("/admin/risk/failure-first", {})); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failure demo could not run."); } finally { setRunning(false); } }
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-wider text-danger-text">Razorpay Admin · Risk & Exceptions</p><h1 className="mt-1 text-2xl font-bold">Failure-first payment safety</h1><p className="mt-2 text-sm text-ink-muted">Demonstrate why a failed provider status must never be interpreted as “customer was not debited.”</p></header>
    <section className="rounded-card border border-border bg-surface p-6"><div className="flex items-start gap-3"><AlertTriangle className="text-warning" /><div><h2 className="font-bold">Debit-credit mismatch scenario</h2><p className="mt-1 text-sm text-ink-muted">Loads persisted financial evidence from the backend and proves that automatic retry remains blocked.</p></div></div><button disabled={running} onClick={() => void run()} className="mt-5 rounded-md bg-danger px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{running ? "Loading evidence…" : "Run one-click failure demo"}</button>{error ? <p className="mt-4 rounded-md bg-danger-subtle p-3 text-sm text-danger-text">{error}</p> : null}</section>
    {result ? <section className="space-y-4 rounded-card border-2 border-danger/40 bg-surface p-6"><div className="flex items-center justify-between"><h2 className="font-bold text-danger-text">{result.classification}</h2><span className="rounded-full bg-danger-subtle px-3 py-1 text-xs font-bold text-danger-text">RISK {result.risk.score}/100 · {result.risk.level}</span></div><div className="grid gap-3 md:grid-cols-4"><Fact label="Amount" value={formatMoney({ amountMinor: result.payment.amountMinor, currency: result.payment.currency })} /><Fact label="Payment" value={result.payment.state} /><Fact label="Customer debit" value={result.payment.customerDebitStatus} /><Fact label="Merchant credit" value={result.payment.merchantCreditStatus} /></div><div className="flex items-start gap-2 rounded-md bg-danger-subtle p-4 text-sm text-danger-text"><Ban size={17} className="mt-0.5 shrink-0" /><div><p className="font-bold">AUTOMATIC RETRY {result.automaticRetry}</p><p className="mt-1">{result.reason}</p><p className="mt-2 text-xs">{result.risk.reasons.join(" · ")}</p></div></div><div className="flex items-center gap-2 text-sm text-ink-muted"><Search size={15} />Next action: investigation and reconciliation required.</div><div className="flex items-center gap-2 text-xs text-success-text"><ShieldCheck size={14} />Evidence loaded from Payment {result.payment.id.slice(0, 8)}…</div></section> : null}
  </div>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-surface-subtle p-3"><p className="text-xs text-ink-faint">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
