import { CheckCircle2, CircleAlert, Store } from "lucide-react";
import { useMarketplaceDiscovery } from "../hooks/use-api";
import { ErrorState, Skeleton } from "../components/ui/States";

export default function AdminMerchantsPage() {
  const marketplace = useMarketplaceDiscovery();
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-wider text-brand-600">Razorpay Admin</p><h1 className="mt-1 text-2xl font-bold">Merchant onboarding & AI readiness</h1><p className="mt-2 text-sm text-ink-muted">Govern which merchants are discoverable and ready for bounded agentic checkout.</p></header>
    {marketplace.isLoading ? <Skeleton className="h-64" /> : marketplace.isError ? <ErrorState message="Could not load merchants." onRetry={() => marketplace.refetch()} /> : <div className="space-y-3">{marketplace.data?.merchants.map((merchant) => { const ready = merchant.products.filter((product) => product.readiness.state === "AGENT_READY").length; const blockers = merchant.products.flatMap((product) => product.readiness.missingCritical).length; return <article key={merchant.merchantId} className="grid gap-4 rounded-card border border-border bg-surface p-5 md:grid-cols-[1fr_auto_auto_auto] md:items-center"><div className="flex items-center gap-3"><div className="rounded-lg bg-brand-50 p-2 text-brand-600"><Store size={18} /></div><div><h2 className="font-bold">{merchant.name}</h2><p className="text-xs text-ink-muted">{merchant.businessCategory} · {merchant.slug}</p></div></div><div><p className="text-xs text-ink-faint">Catalog</p><p className="text-sm font-semibold">{merchant.products.length} products</p></div><div><p className="text-xs text-ink-faint">AI-ready</p><p className="text-sm font-semibold">{ready}/{merchant.products.length}</p></div><div className={blockers ? "inline-flex items-center gap-1 text-xs font-semibold text-warning-text" : "inline-flex items-center gap-1 text-xs font-semibold text-success-text"}>{blockers ? <CircleAlert size={14} /> : <CheckCircle2 size={14} />}{blockers ? `${blockers} blockers` : "Enabled"}</div></article>; })}</div>}
  </div>;
}
