import { useState } from "react";
import { Gauge, Info, RotateCw } from "lucide-react";
import { READINESS_DIMENSIONS, READINESS_DIMENSION_LABEL } from "@razorgrowth/domain";
import { useReadinessHistory, useReadinessLatest, useRecalculateReadiness } from "../hooks/use-api";
import { Card, CardBody, CardHeader, CardTitle } from "../components/ui/Card";
import { EmptyState, ErrorState, Skeleton } from "../components/ui/States";
import { DemoDataBadge } from "../components/ui/DemoDataBadge";
import { ReadinessLevelBadge } from "../components/readiness/ReadinessLevelBadge";
import { BlockerCard } from "../components/readiness/BlockerCard";
import { DimensionBar } from "../components/readiness/DimensionBar";
import { ScoreRing } from "../components/readiness/ScoreRing";
import { formatDateTime } from "../lib/format";
import { ApiError } from "../lib/api-client";
import { PageHeader } from "../components/layout/PageHeader";

function DeltaValue({ value }: { value: number }) {
  if (value === 0) return <span className="text-ink-faint">no change</span>;
  const positive = value > 0;
  return (
    <span className={positive ? "text-success-text" : "text-danger-text"}>
      {positive ? "+" : ""}
      {value}
    </span>
  );
}

export default function ReadinessPage() {
  const { data, isLoading, isError, error, refetch } = useReadinessLatest();
  const history = useReadinessHistory(10);
  const recalculate = useRecalculateReadiness();
  const [expandedDimension, setExpandedDimension] = useState<string | null>(null);

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <PageHeader
          title={"Readiness Score"}
          lead={"How ready your catalogue is for AI buyers, and exactly which products are holding the score back."}
        />
          <p className="mt-1 max-w-2xl text-sm text-ink-muted">
            Whether AI buyers can reliably <span className="text-ink">discover</span>,{" "}
            <span className="text-ink">understand</span>, <span className="text-ink">compare</span>,{" "}
            <span className="text-ink">select</span>, <span className="text-ink">check out</span>, and{" "}
            <span className="text-ink">transact</span> using this merchant&rsquo;s structured commerce data.
            Computed from real catalog, policy, and payment evidence — never generated by a language model.
          </p>
        </div>
        <button
          type="button"
          onClick={() => recalculate.mutate()}
          disabled={recalculate.isPending}
          className="inline-flex shrink-0 items-center gap-1.5 rounded-md border border-border bg-surface px-3 py-1.5 text-sm font-medium text-ink hover:bg-surface-subtle disabled:cursor-not-allowed disabled:opacity-50"
        >
          <RotateCw size={14} className={recalculate.isPending ? "animate-spin" : ""} />
          {recalculate.isPending ? "Analyzing catalog readiness…" : "Recalculate Readiness"}
        </button>
      </div>

      {isLoading ? (
        <Card>
          <CardBody>
            <Skeleton className="h-48 w-full" />
          </CardBody>
        </Card>
      ) : isError ? (
        <Card>
          <ErrorState
            message={error instanceof ApiError ? error.message : "Could not load the readiness snapshot."}
            onRetry={() => refetch()}
          />
        </Card>
      ) : !data ? (
        <Card>
          <EmptyState
            icon={<Gauge size={18} />}
            title="Readiness has not been calculated yet"
            description="Once catalog, policy, and payment data exist for this merchant, a readiness snapshot will appear here."
          />
        </Card>
      ) : (
        <>
          <Card>
            <CardHeader className="flex flex-wrap items-center gap-2">
              <CardTitle>Overall Score</CardTitle>
              <ReadinessLevelBadge level={data.snapshot.level} />
              {data.snapshot.isSyntheticDemo ? <DemoDataBadge /> : null}
              <span className="ml-auto text-xs text-ink-faint">
                v{data.snapshot.calculationVersion} · {formatDateTime(data.snapshot.createdAt)}
              </span>
            </CardHeader>
            <CardBody className="grid gap-6 md:grid-cols-[auto_1fr]">
              <div className="flex flex-col items-center justify-center gap-2 rounded-card bg-surface-subtle px-6 py-6">
                <ScoreRing score={data.snapshot.overallScore} size={144} />
                {data.delta ? (
                  <span className="text-xs font-medium">
                    <DeltaValue value={data.delta.overallScoreDelta} /> since last analysis
                  </span>
                ) : null}
              </div>
              <div className="space-y-3">
                {READINESS_DIMENSIONS.map((dimension) => (
                  <button
                    key={dimension}
                    type="button"
                    onClick={() => setExpandedDimension(expandedDimension === dimension ? null : dimension)}
                    className="block w-full text-left"
                  >
                    <DimensionBar
                      label={READINESS_DIMENSION_LABEL[dimension]}
                      score={data.snapshot.dimensions[dimension]}
                    />
                  </button>
                ))}
              </div>
            </CardBody>
          </Card>

          {expandedDimension ? (
            <Card>
              <CardHeader>
                <CardTitle>Why {READINESS_DIMENSION_LABEL[expandedDimension as keyof typeof READINESS_DIMENSION_LABEL]}?</CardTitle>
              </CardHeader>
              <CardBody className="space-y-2 text-sm text-ink-muted">
                {data.snapshot.blockers.filter((b) => b.dimension === expandedDimension).length === 0 ? (
                  <p>No specific blockers were identified for this dimension in the latest analysis.</p>
                ) : (
                  data.snapshot.blockers
                    .filter((b) => b.dimension === expandedDimension)
                    .map((b) => (
                      <p key={b.code}>
                        {b.explanation} <span className="text-ink-faint">— {b.remediation}</span>
                      </p>
                    ))
                )}
                {data.delta ? (
                  <p className="text-xs text-ink-faint">
                    Changed <DeltaValue value={data.delta.dimensionDeltas[expandedDimension] ?? 0} /> since the
                    previous analysis.
                  </p>
                ) : null}
              </CardBody>
            </Card>
          ) : null}

          <div className="grid gap-6 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Why this score?</CardTitle>
              </CardHeader>
              <CardBody className="space-y-3 text-sm">
                <p>
                  <span className="font-medium text-ink">Strongest dimension:</span>{" "}
                  <span className="text-ink-muted">{data.snapshot.strongestDimension}</span>
                </p>
                <p>
                  <span className="font-medium text-ink">Largest readiness gap:</span>{" "}
                  <span className="text-ink-muted">{data.snapshot.weakestDimension}</span>
                </p>
                {data.snapshot.strengths.length > 0 ? (
                  <ul className="space-y-1 text-ink-muted">
                    {data.snapshot.strengths.map((s) => (
                      <li key={s} className="flex gap-2">
                        <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-success" />
                        {s}
                      </li>
                    ))}
                  </ul>
                ) : null}
              </CardBody>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Deterministic recommendations</CardTitle>
              </CardHeader>
              <CardBody>
                {data.snapshot.recommendations.length === 0 ? (
                  <p className="text-sm text-ink-muted">Every dimension currently meets its target threshold.</p>
                ) : (
                  <ul className="space-y-2 text-sm text-ink-muted">
                    {data.snapshot.recommendations.map((rec) => (
                      <li key={rec} className="flex gap-2">
                        <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-500" />
                        {rec}
                      </li>
                    ))}
                  </ul>
                )}
              </CardBody>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Readiness blockers, prioritized</CardTitle>
            </CardHeader>
            <CardBody>
              {data.snapshot.blockers.length === 0 ? (
                <p className="text-sm text-ink-muted">No blockers were identified in the latest analysis.</p>
              ) : (
                <div className="space-y-3">
                  {data.snapshot.blockers.map((blocker, i) => (
                    <BlockerCard key={blocker.code} blocker={blocker} rank={i + 1} />
                  ))}
                </div>
              )}
            </CardBody>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>History</CardTitle>
            </CardHeader>
            <CardBody>
              {history.isLoading ? (
                <Skeleton className="h-16 w-full" />
              ) : !history.data || history.data.items.length <= 1 ? (
                <p className="text-sm text-ink-muted">No previous readiness analysis available.</p>
              ) : (
                <ul className="space-y-2 text-sm">
                  {history.data.items.map((snap) => (
                    <li key={snap.id} className="flex items-center justify-between border-b border-border pb-2 last:border-0">
                      <span className="text-ink-muted">{formatDateTime(snap.createdAt)}</span>
                      <span className="flex items-center gap-2">
                        <span className="font-medium text-ink">{snap.overallScore}/100</span>
                        <ReadinessLevelBadge level={snap.level} />
                      </span>
                    </li>
                  ))}
                </ul>
              )}
            </CardBody>
          </Card>

          <Card>
            <CardBody className="flex gap-3 text-sm text-ink-muted">
              <Info size={16} className="mt-0.5 shrink-0 text-ink-faint" />
              <p>
                Each dimension is computed from real, inspectable data — for example, Policy Completeness
                reflects the share of products with structured return and shipping information. Recommendations
                are produced by fixed threshold rules, not by an AI model, so every suggestion here can be traced
                back to the exact metric that produced it.
              </p>
            </CardBody>
          </Card>
        </>
      )}
    </div>
  );
}
