-- PART 10 §1 — real merchant/approver identity: MerchantUser (real,
-- password-authenticated, RBAC-scoped), Session (opaque, revocable,
-- hashed-token), and Approval.approverId gains real referential
-- integrity to MerchantUser instead of being a free-form string that
-- happened to always equal a fixed constant.

-- CreateEnum
CREATE TYPE "MerchantUserRole" AS ENUM ('OWNER', 'APPROVER', 'VIEWER');

-- CreateTable
CREATE TABLE "MerchantUser" (
    "id" TEXT NOT NULL,
    "merchantId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "MerchantUserRole" NOT NULL DEFAULT 'OWNER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MerchantUser_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "MerchantUser_email_key" ON "MerchantUser"("email");

-- CreateIndex
CREATE INDEX "MerchantUser_merchantId_idx" ON "MerchantUser"("merchantId");

-- AddForeignKey
ALTER TABLE "MerchantUser" ADD CONSTRAINT "MerchantUser_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "merchantUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");

-- CreateIndex
CREATE INDEX "Session_merchantUserId_idx" ON "Session"("merchantUserId");

-- CreateIndex
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_merchantUserId_fkey" FOREIGN KEY ("merchantUserId") REFERENCES "MerchantUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Existing Approval rows (100% synthetic demo data) all carry the old
-- fixed-constant "demo-merchant-owner" approverId, which is not a real
-- MerchantUser row and would violate the new foreign key below. This
-- table is fully regenerated by `pnpm db:seed` immediately after this
-- migration runs, matching the same precedent set in PART 05's own
-- migration (clearing AgentAction rows predating the hash-chain
-- requirement) — never a real-world data-loss concern in this demo
-- environment. ExecutionAuthorization.approvalId (onDelete: Restrict)
-- must be cleared first, or the delete below would be blocked.
UPDATE "ExecutionAuthorization" SET "approvalId" = NULL WHERE "approvalId" IS NOT NULL;
DELETE FROM "Approval";

-- AddForeignKey
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_approverId_fkey" FOREIGN KEY ("approverId") REFERENCES "MerchantUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
